import Vue from 'vue';
import Vuex from 'vuex';
Vue.use(Vuex);
export default new Vuex.Store({
	strict:true,
	state:{
		showLogin:true,
		shouldLogin:false,
		searchInfo:{
			destination:'',
			longitude:113.14224,
			latitude:23.06015,
			stime:null,
			etime:null,
			keyword:'',
			minPrice:0,
			maxPrice:500,
			star:0
		},
		searchResult:true,
		hotelList:[],
		roomList:[],
		currentHotel:{},
		currentRoomId:0,
		phone:"",
		userName:'',
		userInfo:{},
		currentPosition:{},
		orderId:'',
		totalAmount:0,
		orderState:'',
		orderTime:null,
		wxInfo:null,
		openId:'',
	},
	getters:{
		currentHotelId(state){
			return state.currentHotel.id;
		}
	},
	mutations:{
		changeLogin(state,show){
			state.showLogin=show;
		},
		changeShouldLogin(state,should){
			state.shouldLogin=should;
		},
		changeStar(state,star){
			state.searchInfo.star=star;
		},
		changePrice(state,price){
			state.searchInfo.minPrice=price[0];
			state.searchInfo.maxPrice=price[1];
		},
		changeKeyword(state,keyword){
			state.searchInfo.keyword=keyword;
		},
		changeTime(state,time){
			state.searchInfo.stime=time.stime;
			state.searchInfo.etime=time.etime;
		},
		changeDestination(state,des){
			state.searchInfo.destination=des;
		},
		saveHotelList(state,data){
			state.hotelList=data;
		},
		saveHotel(state,data){
			state.currentHotel=data;
		},
		saveComCount(state,count){
			state.currentHotel.comCount=count;
		},
		saveHotelCity(state,city){
			state.currentHotel.branchCity=city;
		},
		saveRoomList(state,data){
			state.roomList=data;
		},
		savePosition(state,pos){
			state.searchInfo.longitude=pos.longitude;
			state.searchInfo.latitude=pos.latitude;
		},
		saveCurrentPosition(state,pos){
			state.currentPosition=pos;
		},
		saveHotelId(state,id){
			state.currentHotelId=id;
		},
		saveRoomId(state,id){
			state.currentRoomId=id;
		},
		saveUserPhone(state,phone){
			state.userPhone=phone;
		},
		saveUserName(state,name){
			state.userName=name;
		},
		saveLoginInfo(state,data){
			state.phone=data.phone;
			state.userInfo=data;
		},
		saveOrderId(state,id){
			state.orderId=id;
		},
		saveOrderTime(state,time){
			state.orderTime=time;
		},
		saveTotalAmount(state,amount){
			state.totalAmount=amount;
		},
		changeSearchResult(state,b){
			state.searchResult=b;
		},
		changeOrderState(state,s){
			state.orderState=s;
		},
		saveWxInfo(state,info){
			state.wxInfo=info;
		},
		saveOpenId(state,id){
			state.openId=id;
		}
	}
})